application: rent-rocket
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:

- name: django
  version: "1.4"
- name: MySQLdb
  version: "latest"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'rentrocket.settings'

handlers:

- url: /static
  static_dir: static
  expiration: '0'

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /.*
  script: main.application
  
